---
name: 'sbomify'
description: 'A GitHub Action to upload an SBOM CycloneDX or SPDX to sbomify'
author: 'sbomify'
inputs:
  token:
    description: 'Authorization token for sbomify API'
    required: true
  sbom-file:
    description: 'Path to the SBOM file to be uploaded'
    required: true
runs:
  using: 'composite'
  steps:
    - run: ./entrypoint.sh ${{ inputs.token }} ${{ inputs.sbom-file }}
      shell: bash

branding:
  icon: 'upload-cloud'
  color: 'blue'
