---
name: Docker Build/Checks

on:  # yamllint disable-line rule:truthy
  push: null
  pull_request: null

jobs:
  build:
    name: Docker Build/Checks
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Simulate GitHub Actions run
      - uses: sbomify/github-action@$GITHUB_SHA
        name: Test Run
        env:
          TOKEN: placeholder
          COMPONENT_ID: placeholder
          UPLOAD: false
          SBOM_FILE: tests/test-data/syft.cdx.json
