---
name: Integration Tests

on:  # yamllint disable-line rule:truthy
  push: null
  pull_request: null

jobs:
  build:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Poetry
        run: |
          python -m pip install pipx --no-cache
          pipx install poetry --global
          pipx ensurepath --global

      - name: Install virtual environment
        run: |
          poetry install

      # This is admittably somewhat naive testing, but bether than nothing.
      - name: Run tests
        run: |
          PYTHONPATH=$(pwd) \
            poetry run python tests/test_entrypoint.py
