---

name: Upload an SBOM to sbomify

on:
  branches:
    - master

jobs:
  upload-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload SBOM
        uses: sbomify/github-action@master
        env:
          TOKEN: ${{ secrets.SBOMIFY_TOKEN }}
          COMPONENT_ID: 'Gu9wem8mkX'
          SBOM_FILE: 'poetry.lock'
          AUGMENT: false
          ENRICH: true
          UPLOAD: true
